window.SPEC_HUB_INVENTORY = {
  "schemaVersion": 1,
  "repository": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge",
  "branch": "main",
  "generatedAt": "2026-09-30T06:52:52.300Z",
  "baselineVersion": "2026-09-29-v1",
  "sourceManifest": "core/v1.0/hub-manifest.json",
  "sourceStatus": "specs/spec-status.json",
  "statusDefinitions": {
    "not-started": "尚未建立規格",
    "ai-draft": "AI 草稿已建立",
    "needs-review": "等待人工確認",
    "queryable": "已可供查詢",
    "product-confirmed": "產品規則已確認",
    "dev-qa-ready": "開發與 QA 規格完整"
  },
  "queryableStatuses": [
    "queryable",
    "product-confirmed",
    "dev-qa-ready"
  ],
  "currentUser": null,
  "specs": [
    {
      "id": "forgot-password-reset",
      "canonicalId": "forgot-password-reset",
      "canonicalIds": [
        "forgot-password-reset-content",
        "password-reset-flow-action-button",
        "password-requirement-alert"
      ],
      "title": "忘記密碼與重設密碼",
      "module": "登入與帳號安全",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=forgot-password-reset.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "first-login-password-reset",
      "canonicalId": "first-login-password-reset",
      "canonicalIds": [
        "first-login-password-reset-content",
        "password-reset-flow-action-button",
        "password-requirement-alert"
      ],
      "title": "首次登入重設密碼",
      "module": "登入與帳號安全",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=first-login-password-reset.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "two-factor-authentication-setup",
      "canonicalId": "two-factor-authentication-setup",
      "canonicalIds": [
        "two-factor-authentication-setup-content",
        "two-factor-authentication-verification-code-input",
        "two-factor-authentication-flow-action-button",
        "two-factor-authentication-flow-alert"
      ],
      "title": "雙重驗證設定與驗證",
      "module": "登入與帳號安全",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=two-factor-authentication-setup.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "account-management-list",
      "canonicalId": "account-management-list",
      "canonicalIds": [
        "account-management-table-header",
        "account-management-table-row",
        "account-filter-panel-desktop",
        "account-search-filter"
      ],
      "title": "帳號管理列表",
      "module": "系統帳號",
      "priority": "P1",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=account-management-list.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "create-account",
      "canonicalId": "create-account",
      "canonicalIds": [
        "create-account-information",
        "account-form-action-button",
        "account-operation-result"
      ],
      "title": "新增帳號",
      "module": "系統帳號",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=create-account.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "account-details",
      "canonicalId": "account-details",
      "canonicalIds": [
        "account-details",
        "account-overview",
        "detail-info-content"
      ],
      "title": "帳號詳細資訊",
      "module": "系統帳號",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=account-details.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "edit-account",
      "canonicalId": "edit-account",
      "canonicalIds": [
        "edit-account-information",
        "account-form-action-button",
        "account-operation-result"
      ],
      "title": "編輯帳號",
      "module": "系統帳號",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=edit-account.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "account-status-actions",
      "canonicalId": "account-status-actions",
      "canonicalIds": [
        "account-status-section",
        "disable-account-button",
        "delete-account-button",
        "account-operation-result"
      ],
      "title": "帳號停用、啟用與刪除",
      "module": "系統帳號",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=account-status-actions.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "login-security-policy",
      "canonicalId": "login-security-policy",
      "canonicalIds": [
        "login-security-policy",
        "checkbox"
      ],
      "title": "登入安全政策",
      "module": "系統帳號",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=login-security-policy.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "account-two-factor-authentication",
      "canonicalId": "account-two-factor-authentication",
      "canonicalIds": [
        "two-factor-authentication",
        "two-factor-setup-dialog-flow",
        "two-factor-toggle-button",
        "authenticator-status-message"
      ],
      "title": "帳號雙重驗證管理",
      "module": "系統帳號",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=account-two-factor-authentication.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "parameter-category-management",
      "canonicalId": "parameter-category-management",
      "canonicalIds": [
        "parameter-category-table-header",
        "parameter-category-table-row",
        "parameter-category-list-card",
        "parameter-category-search-filter"
      ],
      "title": "參數類別管理列表",
      "module": "資料庫管理",
      "priority": "P1",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=parameter-category-management.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "add-parameter-category",
      "canonicalId": "add-parameter-category",
      "canonicalIds": [
        "add-parameter-category-dialog-content",
        "add-parameter-category-button",
        "enabled-status-field"
      ],
      "title": "新增參數類別",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=add-parameter-category.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "edit-parameter-category",
      "canonicalId": "edit-parameter-category",
      "canonicalIds": [
        "edit-parameter-category-dialog-content",
        "edit-parameter-category-button",
        "enabled-status-field"
      ],
      "title": "編輯參數類別",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=edit-parameter-category.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-subcategory-management",
      "canonicalId": "event-subcategory-management",
      "canonicalIds": [
        "event-subcategory-table-header",
        "event-subcategory-table-row",
        "event-subcategory-mobile-list-card",
        "event-subcategory-search-filter"
      ],
      "title": "事件次類別管理列表",
      "module": "資料庫管理",
      "priority": "P1",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-subcategory-management.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "add-event-subcategory",
      "canonicalId": "add-event-subcategory",
      "canonicalIds": [
        "add-event-subcategory-dialog-content",
        "add-event-subcategory-button"
      ],
      "title": "新增事件次類別",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=add-event-subcategory.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "edit-event-subcategory",
      "canonicalId": "edit-event-subcategory",
      "canonicalIds": [
        "edit-event-subcategory-dialog-content",
        "event-subcategory-action-button"
      ],
      "title": "編輯事件次類別",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=edit-event-subcategory.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-main-category-management",
      "canonicalId": "event-main-category-management",
      "canonicalIds": [
        "event-main-category-table-header",
        "event-main-category-desktop-row",
        "event-main-category-mobile-list",
        "event-main-category-search-filter"
      ],
      "title": "事件主類別管理列表",
      "module": "資料庫管理",
      "priority": "P1",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-main-category-management.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "create-event-main-category",
      "canonicalId": "create-event-main-category",
      "canonicalIds": [
        "create-event-main-category-step-1",
        "create-event-main-category-step-2",
        "create-event-main-category-step-3",
        "create-event-main-category-step-4-upload-image",
        "create-event-main-category-step-4-image-list"
      ],
      "title": "新增事件主類別",
      "module": "資料庫管理",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "queryable",
      "statusLabel": "已可供查詢",
      "reviewStage": "plain-language-reviewed",
      "owner": "未指派",
      "specPath": "specs/create-event-main-category.md",
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "已連結正式規格",
      "documentStatus": "可供查詢，部分規則待確認",
      "summary": "用來建立新的事件主類別。目前流程分成 4 個步驟，依序設定：",
      "questions": [
        "哪些角色可以新增事件主類別。",
        "是否有其他權限條件。",
        "主類別名稱是否必填。",
        "名稱的字數限制。",
        "可輸入的內容或格式限制。",
        "各語系是否都有必填要求。",
        "不同語系資料之間的保存與送出規則。",
        "是否可以完全不選事件次類別。",
        "最多可以選擇幾個事件次類別。",
        "是否有其他選擇限制。",
        "是否可以完全不選發布介面。",
        "圖片是否必填。",
        "支援哪些圖片格式。",
        "圖片尺寸限制。",
        "圖片容量限制。",
        "圖片數量限制。",
        "返回前一步後，原本已輸入或已選擇的資料是否保留。",
        "關閉視窗時，已輸入資料如何處理。",
        "按下「取消」時，已輸入資料如何處理。",
        "使用「清空內容並重新填寫」時，是否需要再次確認。",
        "關閉、取消或清空後，資料是否會被保存。",
        "各欄位實際驗證條件。",
        "各步驟錯誤畫面的觸發條件。",
        "驗證失敗時的錯誤訊息。",
        "API 失敗或其他系統錯誤如何處理。",
        "Step 4 按下「新增」後實際會建立哪些資料。",
        "新增成功的判定方式。",
        "新增成功後何時生效。",
        "新增成功後導向哪個畫面。",
        "新增失敗時如何處理。"
      ],
      "openQuestions": 30,
      "screenCount": 4,
      "updatedAt": "2026-09-29",
      "nextAction": "回答缺漏問題並同步正式規格",
      "isQueryable": true,
      "links": {
        "spec": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/create-event-main-category.md",
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/edit/main/specs/create-event-main-category.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/create-event-main-category.md",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "edit-event-main-category",
      "canonicalId": "edit-event-main-category",
      "canonicalIds": [
        "edit-event-main-category-step-1",
        "edit-event-main-category-step-2",
        "edit-event-main-category-step-3",
        "edit-event-main-category-step-4-upload-image",
        "edit-event-main-category-step-4-image-list"
      ],
      "title": "編輯事件主類別",
      "module": "資料庫管理",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "queryable",
      "statusLabel": "已可供查詢",
      "reviewStage": "base-spec-only",
      "owner": "未指派",
      "specPath": "specs/edit-event-main-category.md",
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "已連結正式規格",
      "documentStatus": "可供查詢，部分規則待確認",
      "summary": "用來修改既有事件主類別的名稱、掛載次類別、發布介面與圖片。",
      "questions": [
        "哪些角色可以編輯，以及不同角色可修改哪些欄位。",
        "Step 2 修改掛載次類別時是否可以全部清空，以及最多可選幾個。",
        "Step 3 是否可以不選任何發布介面。",
        "Step 4 圖片格式、尺寸、容量、數量與刪除既有圖片的規則。",
        "返回、關閉、取消或清空時，如何保留或還原既有資料。",
        "編輯完成後何時生效，以及是否同步至其他系統。",
        "各欄位錯誤狀態的觸發條件。"
      ],
      "openQuestions": 7,
      "screenCount": 5,
      "updatedAt": "2026-09-23",
      "nextAction": "交給普通 AI 白話整理",
      "isQueryable": true,
      "links": {
        "spec": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/edit-event-main-category.md",
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/edit/main/specs/edit-event-main-category.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/edit-event-main-category.md",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-main-category-subcategory-viewer",
      "canonicalId": "event-main-category-subcategory-viewer",
      "canonicalIds": [
        "event-main-category-subcategory-viewer",
        "subcategory-list-header",
        "subcategory-list-desktop-row"
      ],
      "title": "查看主類別已掛載次類別",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "low",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-main-category-subcategory-viewer.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-main-category-image-management",
      "canonicalId": "event-main-category-image-management",
      "canonicalIds": [
        "event-main-category-added-image-list",
        "event-main-category-image-filter-group",
        "event-main-category-image-upload-guidance",
        "image-list-header"
      ],
      "title": "事件主類別圖片管理",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-main-category-image-management.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-main-category-image-viewer",
      "canonicalId": "event-main-category-image-viewer",
      "canonicalIds": [
        "event-main-category-image-viewer"
      ],
      "title": "事件主類別圖片檢視",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "low",
      "aiAutomation": "high",
      "status": "queryable",
      "statusLabel": "已可供查詢",
      "reviewStage": "base-spec-only",
      "owner": "未指派",
      "specPath": "specs/event-main-category-image-viewer.md",
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "已連結正式規格",
      "documentStatus": "可供查詢，部分規則待確認",
      "summary": "用來放大查看事件主類別圖片。桌機、平板與手機都有對應畫面，並提供縮放操作。",
      "questions": [
        "哪些角色可以查看圖片。",
        "縮放的最小值、最大值與每次調整幅度。",
        "是否支援下載、另開原圖或其他圖片操作。",
        "圖片載入失敗、圖片不存在或權限不足時的顯示方式。",
        "關閉後是否需要保留前一次的縮放比例。"
      ],
      "openQuestions": 5,
      "screenCount": 3,
      "updatedAt": "2026-09-29",
      "nextAction": "交給普通 AI 白話整理",
      "isQueryable": true,
      "links": {
        "spec": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/event-main-category-image-viewer.md",
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/edit/main/specs/event-main-category-image-viewer.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/event-main-category-image-viewer.md",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "image-path-management",
      "canonicalId": "image-path-management",
      "canonicalIds": [
        "image-path-list-header",
        "image-path-list-desktop-content",
        "image-path-list-mobile",
        "image-path-filter-image-type",
        "image-path-filter-interface"
      ],
      "title": "圖片路徑管理列表",
      "module": "資料庫管理",
      "priority": "P1",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=image-path-management.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "image-path-form",
      "canonicalId": "image-path-form",
      "canonicalIds": [
        "image-path-add-button",
        "image-path-image-type-field",
        "image-path-display-mode-field",
        "image-path-publish-interface-field",
        "image-path-url-field"
      ],
      "title": "新增與編輯圖片路徑",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：確認新增與編輯是否共用同一規格後產生草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "確認新增與編輯是否共用同一規格後產生草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=image-path-form.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "image-path-image-viewer",
      "canonicalId": "image-path-image-viewer",
      "canonicalIds": [
        "image-path-image-viewer"
      ],
      "title": "圖片路徑圖片檢視",
      "module": "資料庫管理",
      "priority": "P2",
      "complexity": "low",
      "aiAutomation": "high",
      "status": "queryable",
      "statusLabel": "已可供查詢",
      "reviewStage": "base-spec-only",
      "owner": "未指派",
      "specPath": "specs/image-path-image-viewer.md",
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "已連結正式規格",
      "documentStatus": "可供查詢，部分規則待確認",
      "summary": "用來從新增或編輯圖片路徑畫面放大查看圖片。支援桌機、平板、手機以及亮色、暗色主題。",
      "questions": [
        "哪些角色可以查看圖片。",
        "縮放的最小值、最大值與每次調整幅度。",
        "手機版圖片旋轉方向及不同圖片比例的顯示規則。",
        "是否支援下載、另開原圖或其他圖片操作。",
        "圖片載入失敗、圖片不存在或權限不足時的顯示方式。"
      ],
      "openQuestions": 5,
      "screenCount": 6,
      "updatedAt": "2026-09-29",
      "nextAction": "交給普通 AI 白話整理",
      "isQueryable": true,
      "links": {
        "spec": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/image-path-image-viewer.md",
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/edit/main/specs/image-path-image-viewer.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/image-path-image-viewer.md",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "global-parameter-management",
      "canonicalId": "global-parameter-management",
      "canonicalIds": [
        "event-parameter-table-header-row",
        "event-parameter-desktop-row",
        "mobile-parameter-list-item",
        "parameter-name-search-filter"
      ],
      "title": "全域參數管理列表",
      "module": "其他設定",
      "priority": "P1",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=global-parameter-management.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "add-global-parameter",
      "canonicalId": "add-global-parameter",
      "canonicalIds": [
        "add-boolean-parameter-dialog",
        "add-date-parameter-dialog",
        "add-json-parameter-dialog",
        "add-number-parameter-dialog",
        "add-text-parameter-dialog"
      ],
      "title": "新增全域參數",
      "module": "其他設定",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=add-global-parameter.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "edit-global-parameter",
      "canonicalId": "edit-global-parameter",
      "canonicalIds": [
        "edit-boolean-parameter-dialog",
        "edit-date-parameter-dialog",
        "edit-json-parameter-dialog",
        "edit-number-parameter-dialog",
        "edit-text-parameter-dialog"
      ],
      "title": "編輯全域參數",
      "module": "其他設定",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=edit-global-parameter.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-parameter-settings",
      "canonicalId": "event-parameter-settings",
      "canonicalIds": [
        "parameter-setting-content",
        "rush-hour-wager-parameter-settings",
        "parameter-category-filter",
        "parameter-keyword-search"
      ],
      "title": "事件參數設定",
      "module": "事件參數管理",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-parameter-settings.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-management-list",
      "canonicalId": "event-management-list",
      "canonicalIds": [
        "event-list-desktop",
        "event-list-tablet-mobile",
        "event-wager-filter",
        "event-status-tabs",
        "event-list-action-group"
      ],
      "title": "事件管理列表",
      "module": "事件設置",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-management-list.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "suggested-event-review-import",
      "canonicalId": "suggested-event-review-import",
      "canonicalIds": [
        "ai-suggested-topic-review-dialog",
        "ai-suggested-topic-item",
        "event-review-table-row",
        "import-topic-button"
      ],
      "title": "AI／第三方建議事件審核與匯入",
      "module": "事件設置",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=suggested-event-review-import.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "topic-event-content-settings",
      "canonicalId": "topic-event-content-settings",
      "canonicalIds": [
        "topic-event-content-settings",
        "topic-event-theme-selector",
        "topic-wager-time-range",
        "wager-options-section-desktop"
      ],
      "title": "議題事件內容設定",
      "module": "事件設置",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：確認新增與編輯狀態分組後產生草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "確認新增與編輯狀態分組後產生草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=topic-event-content-settings.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "sports-event-content-settings",
      "canonicalId": "sports-event-content-settings",
      "canonicalIds": [
        "sports-event-content-settings",
        "sports-event-theme-selector",
        "sports-wager-time-range",
        "sports-wager-options"
      ],
      "title": "運動事件內容設定",
      "module": "事件設置",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：確認新增與編輯狀態分組後產生草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "確認新增與編輯狀態分組後產生草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=sports-event-content-settings.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "timeline-option-event-management",
      "canonicalId": "timeline-option-event-management",
      "canonicalIds": [
        "timeline-option-event-management-pre-wager",
        "timeline-option-event-management-wager-phase",
        "timeline-option-event-management-header"
      ],
      "title": "時間軸選項事件管理",
      "module": "事件設置",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=timeline-option-event-management.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-settlement",
      "canonicalId": "event-settlement",
      "canonicalIds": [
        "settlement-target-event-section",
        "settlement-result-selection-section",
        "settlement-option-result",
        "settlement-event-action-state"
      ],
      "title": "事件結算",
      "module": "事件設置",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-settlement.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "single-parameter-update",
      "canonicalId": "single-parameter-update",
      "canonicalIds": [
        "single-parameter-update-step-1",
        "single-parameter-update-step-2"
      ],
      "title": "單一事件參數更新",
      "module": "事件設置",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "queryable",
      "statusLabel": "已可供查詢",
      "reviewStage": "base-spec-only",
      "owner": "未指派",
      "specPath": "specs/single-parameter-update.md",
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "已連結正式規格",
      "documentStatus": "可供查詢，部分規則待確認",
      "summary": "用來修改單一事件的參數，先編輯內容，再檢查更新前後差異並確認執行。",
      "questions": [
        "哪些角色可以操作，以及可以更新哪些事件。",
        "Step 1 各參數的正式定義、欄位、資料型別與允許值。",
        "Step 1 欄位必填、格式、數值範圍與錯誤條件。",
        "返回、關閉或取消時，修改內容如何處理。",
        "Step 2 確認執行後何時生效，以及是否有版本或同時編輯限制。"
      ],
      "openQuestions": 5,
      "screenCount": 2,
      "updatedAt": "2026-09-23",
      "nextAction": "交給普通 AI 白話整理",
      "isQueryable": true,
      "links": {
        "spec": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/single-parameter-update.md",
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/edit/main/specs/single-parameter-update.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/single-parameter-update.md",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "batch-parameter-update",
      "canonicalId": "batch-parameter-update",
      "canonicalIds": [
        "batch-parameter-update-step-1-2",
        "batch-parameter-update-step-3"
      ],
      "title": "批次事件參數更新",
      "module": "事件設置",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "queryable",
      "statusLabel": "已可供查詢",
      "reviewStage": "base-spec-only",
      "owner": "未指派",
      "specPath": "specs/batch-parameter-update.md",
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "已連結正式規格",
      "documentStatus": "可供查詢，操作規則待確認",
      "summary": "用來對多個已選事件批次修改參數。畫面呈現「確認已選擇事件 → 更改事件參數 → 確認參數更動」三個階段。",
      "questions": [
        "哪些角色可以操作、入口在哪裡，以及可以更新哪些事件。",
        "Step 1 可選事件數量、移除與返回規則。",
        "Step 2 各參數的正式定義、資料型別、允許值、必填與錯誤條件。",
        "前後切換時，已選事件與已輸入參數如何保存。",
        "返回、關閉、取消或中斷時的確認與還原行為。",
        "Step 3 執行後何時生效，以及成功、失敗或部分失敗如何處理。",
        "API、資料寫入、版本與跨系統同步規則。"
      ],
      "openQuestions": 7,
      "screenCount": 3,
      "updatedAt": "2026-09-23",
      "nextAction": "交給普通 AI 白話整理",
      "isQueryable": true,
      "links": {
        "spec": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/batch-parameter-update.md",
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/edit/main/specs/batch-parameter-update.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/batch-parameter-update.md",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "rush-hour-parameter-update",
      "canonicalId": "rush-hour-parameter-update",
      "canonicalIds": [
        "rush-hour-parameter-update-step-1",
        "netwin-profit-range-settings"
      ],
      "title": "Rush Hour 事件參數更新",
      "module": "事件設置",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：確認完整流程步驟後產生草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "確認完整流程步驟後產生草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=rush-hour-parameter-update.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "merchant-event-publication",
      "canonicalId": "merchant-event-publication",
      "canonicalIds": [
        "merchant-publish-dialog",
        "merchant-publish-confirm-dialog",
        "merchant-publish-result-dialog"
      ],
      "title": "事件發布到商戶",
      "module": "事件管理／庫存管理",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=merchant-event-publication.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "force-refund",
      "canonicalId": "force-refund",
      "canonicalIds": [
        "force-refund-dialog",
        "force-refund-event-display",
        "force-refund-round-search",
        "verification-code-field"
      ],
      "title": "強制退款",
      "module": "事件管理／庫存管理",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=force-refund.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "inventory-management-overview",
      "canonicalId": "inventory-management-overview",
      "canonicalIds": [
        "inventory-management-overview",
        "inventory-summary-data",
        "total-inventory-distribution",
        "heatmap-color-legend"
      ],
      "title": "庫存管理總覽",
      "module": "庫存管理",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=inventory-management-overview.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "sell-management-list",
      "canonicalId": "sell-management-list",
      "canonicalIds": [
        "sell-list-header",
        "sell-data-row",
        "sell-order-sort-filter",
        "sell-price-search-input"
      ],
      "title": "出售管理列表",
      "module": "庫存管理",
      "priority": "P1",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=sell-management-list.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "sell-price-and-quantity-update",
      "canonicalId": "sell-price-and-quantity-update",
      "canonicalIds": [
        "sell-price-block",
        "sell-quantity-input",
        "sell-quantity-change-editing",
        "sell-management-result-states"
      ],
      "title": "出售價格與數量調整",
      "module": "庫存管理",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=sell-price-and-quantity-update.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-profit-loss-report",
      "canonicalId": "event-profit-loss-report",
      "canonicalIds": [
        "event-profit-loss-table-header",
        "event-profit-loss-data-row",
        "event-profit-loss-filter-panel-pc-tablet",
        "event-profit-loss-summary-desktop"
      ],
      "title": "事件損益報表",
      "module": "報表記錄",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-profit-loss-report.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "event-profit-loss-report-detail",
      "canonicalId": "event-profit-loss-report-detail",
      "canonicalIds": [
        "event-profit-loss-detail-dialog",
        "event-profit-loss-action-dialog",
        "event-profit-loss-custom-columns-dialog"
      ],
      "title": "事件損益報表詳細資料",
      "module": "報表記錄",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=event-profit-loss-report-detail.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "bet-history-report",
      "canonicalId": "bet-history-report",
      "canonicalIds": [
        "bet-history-table-header",
        "bet-history-data-row",
        "bet-history-member-id-search",
        "bet-history-transaction-id-search"
      ],
      "title": "投分歷史報表",
      "module": "報表記錄",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=bet-history-report.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "bet-history-report-detail",
      "canonicalId": "bet-history-report-detail",
      "canonicalIds": [
        "bet-history-detail-dialog",
        "bet-history-action-dialog",
        "bet-history-custom-columns-dialog",
        "bet-order-info-dialog"
      ],
      "title": "投分歷史詳細資料",
      "module": "報表記錄",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=bet-history-report-detail.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "member-order-history",
      "canonicalId": "member-order-history",
      "canonicalIds": [
        "member-order-header",
        "member-order-row",
        "order-table-header",
        "order-status-filter"
      ],
      "title": "會員訂單紀錄",
      "module": "客服服務",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=member-order-history.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "member-order-detail",
      "canonicalId": "member-order-detail",
      "canonicalIds": [
        "order-detail-dialog",
        "order-detail-item",
        "order-detail-row"
      ],
      "title": "會員訂單詳細資料",
      "module": "客服服務",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=member-order-detail.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "send-order-message",
      "canonicalId": "send-order-message",
      "canonicalIds": [
        "send-order-message-dialog",
        "send-order-message-info",
        "select-order-action-dialog"
      ],
      "title": "發送訂單訊息",
      "module": "客服服務",
      "priority": "P2",
      "complexity": "medium",
      "aiAutomation": "high",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=send-order-message.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "rerun-order",
      "canonicalId": "rerun-order",
      "canonicalIds": [
        "rerun-order-result-dialog",
        "select-order-action-dialog",
        "order-action-trigger"
      ],
      "title": "重新執行訂單",
      "module": "客服服務",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=rerun-order.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "merchant-event-visibility-management",
      "canonicalId": "merchant-event-visibility-management",
      "canonicalIds": [
        "merchant-event-desktop-table-header",
        "merchant-event-desktop-row",
        "merchant-event-mobile-list-item",
        "merchant-event-visibility-status-filter"
      ],
      "title": "商戶事件顯示與隱藏管理",
      "module": "商戶服務",
      "priority": "P1",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=merchant-event-visibility-management.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    },
    {
      "id": "merchant-event-bulk-visibility",
      "canonicalId": "merchant-event-bulk-visibility",
      "canonicalIds": [
        "merchant-event-bulk-visibility-actions",
        "merchant-event-row-selection-cell",
        "merchant-event-row-action-cell"
      ],
      "title": "商戶事件批次顯示與隱藏",
      "module": "商戶服務",
      "priority": "P2",
      "complexity": "high",
      "aiAutomation": "medium",
      "status": "not-started",
      "statusLabel": "尚未建立規格",
      "reviewStage": null,
      "owner": "未指派",
      "specPath": null,
      "sourceIndex": "core/v1.0/page-index.md",
      "sourceStatus": "規格候選，尚未建立正式檔案",
      "documentStatus": "尚未建立",
      "summary": "尚未建立正式規格。下一步：產生 AI 圖文草稿",
      "questions": [],
      "openQuestions": 0,
      "screenCount": 0,
      "updatedAt": "2026-09-29",
      "nextAction": "產生 AI 圖文草稿",
      "isQueryable": false,
      "links": {
        "spec": null,
        "edit": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/new/main/specs?filename=merchant-event-bulk-visibility.md",
        "index": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/core/v1.0/page-index.md",
        "history": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/commits/main/specs/spec-status.json",
        "status": "https://github.com/IsumiOuO/backoffice-design-hub-knowledge/blob/main/specs/spec-status.json"
      }
    }
  ]
};
